### ISSUE TITLE
Falha ao executar o vagrant up

### ISSUE THREAD

**Issue by davidmello** [4linux/541-kubernetes#1]
erro ao executar o vagrant up:

TASK [Instala os pacotes do Kubernetes] ****************************************
fatal: [kube-master]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: W:Updating from such a repository can't be done securely, and is therefore disabled by default., W:See apt-secure(8) manpage for repository creation and user configuration details., W:GPG error: https://prod-cdn.packages.k8s.io/repositories/isv:/kubernetes:/core:/stable:/v1.26/deb  InRelease: The following signatures were invalid: EXPKEYSIG 234654DA9A296436 isv:kubernetes OBS Project <isv:kubernetes@build.opensuse.org>, E:The repository 'https://pkgs.k8s.io/core:/stable:/v1.26/deb  InRelease' is not signed."}

verificando, a chave https://pkgs.k8s.io/core:/stable:/v1.26/deb/Release.key está invalida.

Dentro dos arquivos:
541-kubernetes$ vim provision/ansible/kube-master.yaml 
541-kubernetes$ vim provision/ansible/kube-node1.yaml  
/541-kubernetes$ vim provision/ansible/kube-node2.yaml 

nas linhas 137 e 142 alterando as linhas 
de
https://pkgs.k8s.io/core:/stable:/v1.26/deb/
para
https://pkgs.k8s.io/core:/stable:/v1.31/deb/

e rodando vagrant up, foi.

**Comment by davidmello** [comment]
comentando, testei com 1.27 e 1.29 e não funcionaram.

a partir da 1.30 foi ok no dia de ontem.

**Comment by silvemerson** [comment]
https://github.com/4linux/541-kubernetes/commit/15871a50df661f5df1e47f6434ef50684f1d9adb

Foi realizado a correção v1.28 e o provionamento está em funcionamento.
